### ISSUE TITLE
Error compiling this library ?!

### ISSUE THREAD

**Issue by jessrix** [brunocvcunha/instagram4j#180]
Hey
First off , thank you for your awesome library , Really appreciate it.
I forked this repo today to try and PR add some features to it . But it seems like as i import it into my IDE (All depencies are added) i get some serious errors , Specially in symbol "log" in the main class which i don't see it being defined anywhere and it is reported as "unresolved symbol" . for instance in the line below which "log" is reported as unresolved symbol ..
`log.info("Logging with user " + username + " and password " + password.replaceAll("[a-zA-Z0-9]", "*"));`

I wanted to know if we are allowed to compile this library or our own forks / Is there a piece of code that is not published ?

thanks .

**Comment by jvogit** [comment]
One thing I can think of is lombok. 
I use Eclipe and since this project uses lombok I needed to install lombok for eclipse so the ide doesn't throw errors at me.

You can find instructions here under Install
https://projectlombok.org/

Perhaps this could be your issue of how log is not defined (when it hould be because of log 4 j annotation in lombok?

**Comment by jessrix** [comment]
installed lombok and it works perfectly !
thanks
