### ISSUE TITLE
Errors importing instagram4j.jar as external jar

### ISSUE THREAD

**Issue by DanielePancottini** [brunocvcunha/instagram4j#318]
I have 2 errors when trying to import changed instagram4j.jar as external jar in eclipse.

I would to do some changes on the project to resolve some issues of the library.
I hope to fix this problem.

![IssueInstagram](https://user-images.githubusercontent.com/43572647/57473311-d622b780-728f-11e9-8151-eef5d2e36423.PNG)

**Comment by brunocvcunha** [comment]
There are dependencies to be resolved. Did you set up the project using Maven? Ideally, you should use a dependency manager tool to resolve those for you.

**Comment by DanielePancottini** [comment]
Hi Bruno, thanks for your answer. I'm not using Maven, I use Ivy as dependency manager. My problem is so strange because on ivy's console I haven't got any errors.

**Comment by brunocvcunha** [comment]
It depends on how you configured stuff on your IDE, because you mentioned you added an external JAR, but there are a lot of external jars to bring (the Apache HTTP Client for instance). On Maven, I can do `mvn eclipse:eclipse` and it will configure everything needed to run, there must be something similar on Ivy.

**Comment by DanielePancottini** [comment]
Ok, I'm just played with ivy settings and I have fixed the problem, thanks a lot for the help :grinning:
