### ISSUE TITLE
Hash Password to login

### ISSUE THREAD

**Issue by DanielePancottini** [brunocvcunha/instagram4j#320]
Hi, Is possible to send to instagram4j builder the hashed password insthead the plain text?

**Comment by jemand771** [comment]
As far as I understand the login flow, the password is hashed serverside, so you have to give Instagram4j the plaintext password. I'm not sure though, let's wait for someone to confirm/correct me

**Comment by DanielePancottini** [comment]
Ok thank. Just another question. I have necessity to store the username and the password of a certain user/users in a database. As the login flow I can't store hashed password and reuse it to perform login...is there another method to do what I need?

**Comment by jemand771** [comment]
I don't think so, unfortunately. Thought about storing the cookie as described [here](https://github.com/brunocvcunha/instagram4j/issues/71#issuecomment-336028154), turns out that requires the plaintext password aswell.
Your way to go is to either
- login once to Instagram4j (using the plaintext password) and never quit the application or
- not hash the password you store.

Maybe there is a way to store and reuse the internal token, but that's not implemented yet (and I wouldn't know how to do it either)

**Comment by DanielePancottini** [comment]
Unfortunately I can't store users's instagram passwords as plain text in my database, it's really unsafe...I'm thinking about another solution...I'll think of something.

**Comment by Vioxini** [comment]
Use a custom hash.
Take plain text password, hash the password, store the password and use the unhasher.

**Comment by DanielePancottini** [comment]
@Vioxini Yeah, I've already found a solution to fix my problem which is just what you propose 👍
